"""Detection signals for Provenance Guard.

Signal 1 (this milestone): a Groq-hosted LLM classifier that judges how
AI-generated a piece of text reads and returns a probability P(AI) in 0..1.

Signal 2 (stylometry) arrives in Milestone 4.
"""

import json
import os
import re
from statistics import mean, pstdev

from dotenv import load_dotenv
from groq import Groq

# The API key currently lives in .venv/.env; also honor a repo-root .env or a
# key already exported into the environment. First match wins.
_here = os.path.dirname(os.path.abspath(__file__))
for _candidate in (os.path.join(_here, ".venv", ".env"), os.path.join(_here, ".env")):
    if os.path.exists(_candidate):
        load_dotenv(_candidate)

# Configurable model; default to a capable general-purpose Groq model.
GROQ_MODEL = os.environ.get("GROQ_MODEL", "llama-3.3-70b-versatile")

_SYSTEM_PROMPT = (
    "You are a forensic text classifier. Given a passage, estimate the "
    "probability that it was generated by an AI language model rather than "
    "written by a human. Consider distributional typicality, generic phrasing, "
    "uniform structure, and hedging patterns as AI signals; consider "
    "idiosyncratic voice, uneven emphasis, and personal specificity as human "
    "signals. You are making an estimate, not a determination. "
    'Respond with a JSON object of exactly this shape: '
    '{"ai_probability": <float 0..1>, "reasoning": "<one short sentence>"}'
)


def _clamp01(value) -> float:
    try:
        value = float(value)
    except (TypeError, ValueError):
        return 0.5  # no usable signal -> maximally uncertain
    return max(0.0, min(1.0, value))


def llm_signal(text: str) -> dict:
    """Run the Groq LLM classifier on ``text``.

    Returns ``{"llm_score": float, "reasoning": str}`` where ``llm_score`` is
    P(AI) in 0..1. Never raises for a normal API/parse hiccup — on failure it
    returns a neutral 0.5 so the pipeline degrades gracefully.
    """
    api_key = os.environ.get("GROQ_API_KEY")
    if not api_key:
        return {"llm_score": 0.5, "reasoning": "GROQ_API_KEY not configured; neutral score."}

    client = Groq(api_key=api_key)
    try:
        completion = client.chat.completions.create(
            model=GROQ_MODEL,
            messages=[
                {"role": "system", "content": _SYSTEM_PROMPT},
                {"role": "user", "content": text},
            ],
            temperature=0.0,
            response_format={"type": "json_object"},
        )
        raw = completion.choices[0].message.content
        data = json.loads(raw)
        return {
            "llm_score": _clamp01(data.get("ai_probability")),
            "reasoning": str(data.get("reasoning", "")).strip(),
        }
    except Exception as exc:  # network, parse, or API error -> degrade gracefully
        return {"llm_score": 0.5, "reasoning": f"LLM signal unavailable: {exc}"}


# ---------------------------------------------------------------------------
# Signal 2 — Stylometric heuristics (pure Python, no network)
#
# Measures statistical regularity of surface form. AI writing trends toward
# UNIFORMITY (even sentence lengths, smooth punctuation); human writing is
# BURSTY and irregular. Each sub-metric maps to a 0..1 "AI-uniform" sub-score
# (higher = more AI-like); they combine into one stylometry score.
#
# Calibration constants are module-level so they're easy to tune. Blind spot:
# this signal is meaning-blind — uniform human prose (legal/technical) and
# repetitive poetry both read as "AI" here. Very short text has no stable
# statistics, so we return a neutral 0.5.
# ---------------------------------------------------------------------------

# Sub-score weights (must sum to 1.0). Burstiness is the strongest human/AI
# discriminator, so it dominates; TTR is length-confounded and weak, so it's
# capped low.
STY_W_BURST = 0.60
STY_W_PUNCT = 0.20
STY_W_TTR = 0.20

# Mapping anchors (tuned against the Milestone 4 sample set).
CV_HUMAN = 0.65      # sentence-length coefficient of variation at/above which text reads fully human
PUNCT_AI = 0.20      # punctuation-marks-per-word at/above which density reads fully AI
# TTR is length-confounded: short texts always have high type-token ratio, so
# these anchors are set so that typical short-text values (~0.85) land near
# neutral (~0.5) instead of saturating. Only genuinely repetitive text (low TTR)
# pulls meaningfully toward "human"; TTR's real discriminating power is at the
# low end. Weight is kept modest as a result.
TTR_LO = 0.70        # type-token ratio floor
TTR_HI = 1.00        # type-token ratio ceiling

_SENTENCE_SPLIT = re.compile(r"[.!?]+")
_WORD = re.compile(r"[A-Za-z']+")
_PUNCT_CHARS = ",;:—-()\"'!?."


def _sentences(text: str) -> list[str]:
    return [s.strip() for s in _SENTENCE_SPLIT.split(text) if s.strip()]


def _words(text: str) -> list[str]:
    return _WORD.findall(text)


def _clamp_map(value: float, lo: float, hi: float) -> float:
    """Linearly map value in [lo, hi] to [0, 1], clamped."""
    if hi == lo:
        return 0.5
    return max(0.0, min(1.0, (value - lo) / (hi - lo)))


def stylometry_signal(text: str) -> dict:
    """Compute the stylometry signal.

    Returns ``{"sty_score": float, "metrics": {...}}`` where ``sty_score`` is a
    0..1 estimate of AI-likelihood based purely on surface form.
    """
    words = _words(text)
    sentences = _sentences(text)
    n_words = len(words)

    # Not enough text for stable statistics -> no signal, stay neutral.
    if n_words < 8 or len(sentences) < 2:
        return {
            "sty_score": 0.5,
            "metrics": {"note": "insufficient text for stable stylometry", "n_words": n_words},
        }

    sent_lengths = [len(_words(s)) for s in sentences]
    mean_len = mean(sent_lengths)
    cv = (pstdev(sent_lengths) / mean_len) if mean_len else 0.0

    ttr = len(set(w.lower() for w in words)) / n_words
    punct_density = sum(text.count(c) for c in _PUNCT_CHARS) / n_words

    # Sub-scores: higher = more AI-like.
    s_burst = 1.0 - _clamp_map(cv, 0.0, CV_HUMAN)          # low variance -> AI
    s_punct = _clamp_map(punct_density, 0.0, PUNCT_AI)     # dense/even punctuation -> AI
    s_ttr = _clamp_map(ttr, TTR_LO, TTR_HI)                # very diverse vocab -> AI (weak)

    sty_score = STY_W_BURST * s_burst + STY_W_PUNCT * s_punct + STY_W_TTR * s_ttr
    sty_score = max(0.0, min(1.0, sty_score))

    return {
        "sty_score": round(sty_score, 3),
        "metrics": {
            "sentence_length_cv": round(cv, 3),
            "mean_sentence_len": round(mean_len, 2),
            "type_token_ratio": round(ttr, 3),
            "punct_density": round(punct_density, 3),
            "sub_burstiness": round(s_burst, 3),
            "sub_punct": round(s_punct, 3),
            "sub_ttr": round(s_ttr, 3),
        },
    }


if __name__ == "__main__":
    # Independent test harness: call the signal directly and inspect output.
    samples = {
        "human_porch": (
            "The sun dipped below the horizon, painting the sky in hues of amber "
            "and rose. I sat on the porch, coffee in hand, watching the "
            "neighborhood slowly go quiet."
        ),
        "ai_flavored": (
            "In today's fast-paced digital landscape, leveraging synergistic "
            "solutions is crucial. Moreover, organizations must prioritize "
            "scalable frameworks to optimize outcomes and drive value."
        ),
    }
    for name, sample in samples.items():
        result = llm_signal(sample)
        print(f"{name}: {json.dumps(result, ensure_ascii=False)}")
